package config

import "testing"

func TestCheckBcryptHash(t *testing.T) {
	tests := []struct {
		name string
		hash string
		ok   bool
	}{
		{"generated by hash-password", "$2a$10$g8J.N1mZm6FUHfQR5FMYButGpMFIZeYtnd4aJd6sp.gXQQ.LQmUDq", true},
		{"2y variant", "$2y$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy", true},
		// The hash this project shipped as its default until it turned out no
		// password could match it: the `=` cannot come out of bcrypt.
		{"padding left in", "$2a$10$eImiTXuWVxfM37uY4JANjQ=.YKFqvGpH5B6z0Nn9RyVBVRxbTvFDW", false},
		{"truncated digest", "$2a$10$g8J.N1mZm6FUHfQR5FMYBu", false},
		{"plain text", "hunter2", false},
		{"empty", "", false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			err := checkBcryptHash(tc.hash)
			if tc.ok && err != nil {
				t.Fatalf("expected the hash to be accepted, got %v", err)
			}
			if !tc.ok && err == nil {
				t.Fatal("expected the hash to be rejected, it was accepted")
			}
		})
	}
}

// The defaults shipped in the chart and the example config are what most people
// will start from, so they have to be usable as written.
func TestShippedDefaultHashIsUsable(t *testing.T) {
	const shipped = "$2a$10$g8J.N1mZm6FUHfQR5FMYButGpMFIZeYtnd4aJd6sp.gXQQ.LQmUDq"
	if err := checkBcryptHash(shipped); err != nil {
		t.Fatalf("the default passwordHash in values.yaml is unusable: %v", err)
	}
}
