package config

import "testing"

func TestCheckBcryptHash(t *testing.T) {
	tests := []struct {
		name string
		hash string
		ok   bool
	}{
		{"generated by hash-password", "$2a$10$g8J.N1mZm6FUHfQR5FMYButGpMFIZeYtnd4aJd6sp.gXQQ.LQmUDq", true},
		{"2y variant", "$2y$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy", true},
		// The hash this project shipped as its default until it turned out no
		// password could match it: the `=` cannot come out of bcrypt.
		{"padding left in", "$2a$10$eImiTXuWVxfM37uY4JANjQ=.YKFqvGpH5B6z0Nn9RyVBVRxbTvFDW", false},
		{"truncated digest", "$2a$10$g8J.N1mZm6FUHfQR5FMYBu", false},
		{"plain text", "hunter2", false},
		{"empty", "", false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			err := checkBcryptHash(tc.hash)
			if tc.ok && err != nil {
				t.Fatalf("expected the hash to be accepted, got %v", err)
			}
			if !tc.ok && err == nil {
				t.Fatal("expected the hash to be rejected, it was accepted")
			}
		})
	}
}

// The defaults shipped in the chart and the example config are what most people
// will start from, so they have to be usable as written.
func TestShippedDefaultHashIsUsable(t *testing.T) {
	const shipped = "$2a$10$g8J.N1mZm6FUHfQR5FMYButGpMFIZeYtnd4aJd6sp.gXQQ.LQmUDq"
	if err := checkBcryptHash(shipped); err != nil {
		t.Fatalf("the default passwordHash in values.yaml is unusable: %v", err)
	}
}

func TestAuditReadIsOfferedOnlyWhenThereIsATrailToRead(t *testing.T) {
	has := func(c *Config) bool {
		for _, op := range Operations(c) {
			if op == OpAuditRead {
				return true
			}
		}
		return false
	}

	if has(&Config{}) {
		t.Error("audit-read was offered with no Loki and no cluster: the page would have nothing to show")
	}
	if !has(&Config{Logs: LogsConfig{LokiURL: "http://loki:3100"}}) {
		t.Error("audit-read was not offered although Loki is configured")
	}
	if !has(&Config{Cluster: ClusterConfig{InCluster: true}}) {
		t.Error("audit-read was not offered although the service can read its own pod logs")
	}
}

func TestAGrantForASwitchedOffFeatureDoesNotBreakStartup(t *testing.T) {
	// The shipped roles mention audit-read. An installation with neither Loki
	// nor a cluster to read its own logs in has no audit page — and must still
	// start, rather than refusing on a grant it simply cannot use.
	off := &Config{}
	r := &RBACConfig{
		Operations: Operations(off),
		Roles: map[string]RoleSpec{
			"platform-admin": {
				Namespaces: []NamespaceGrant{{Namespace: "*", Operations: []string{"*"}}},
				Global:     []string{OpUserList, OpUserManage, OpAuditRead},
			},
		},
	}
	if err := r.Validate(); err != nil {
		t.Fatalf("a grant for a disabled feature was refused: %v", err)
	}

	// A name no build has ever known is still a typo, and still refused.
	r.Roles["platform-admin"] = RoleSpec{Global: []string{"audit-reed"}}
	if err := r.Validate(); err == nil {
		t.Fatal("a misspelled operation was accepted")
	}
}

func TestTheStorageBackendIsChecked(t *testing.T) {
	base := func() *Config {
		return &Config{
			Storage: StorageConfig{Path: "/data/devops-tools.json"},
			Cluster: ClusterConfig{InCluster: true},
			Auth: AuthConfig{
				Provider: ProviderLocal,
				Bootstrap: BootstrapConfig{
					Users: []string{"admin"},
					Roles: []string{"platform-admin"},
					PasswordLogin: BootstrapLogin{
						Username:     "admin",
						PasswordHash: "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
					},
				},
			},
		}
	}

	t.Run("empty means file, so older configurations keep working", func(t *testing.T) {
		if err := base().Validate(); err != nil {
			t.Fatal(err)
		}
	})

	t.Run("a misspelled backend is refused", func(t *testing.T) {
		c := base()
		c.Storage.Backend = "kubernets"
		if err := c.Validate(); err == nil {
			t.Fatal("accepted")
		}
	})

	t.Run("the Kubernetes backend needs a cluster", func(t *testing.T) {
		c := base()
		c.Storage.Backend = StorageKubernetes
		c.Cluster.InCluster = false
		if err := c.Validate(); err == nil {
			t.Fatal("accepted: outside a cluster there is no Secret to keep the model in")
		}
	})
}

func TestEveryOperationBelongsToASection(t *testing.T) {
	// The role editor draws its checkboxes from these three lists. An operation
	// in none of them exists in the code, can be granted by editing the store by
	// hand, and has no checkbox — which is exactly how audit-read and
	// access-restore were each unreachable for a while.
	sections := map[string]bool{}
	for _, group := range [][]string{NamespaceOperations(), GlobalOperations(), ConfigOperations()} {
		for _, op := range group {
			sections[op] = true
		}
	}

	full := &Config{
		Logs:         LogsConfig{LokiURL: "http://loki:3100"},
		Configs:      ConfigsConfig{Consul: ConsulSourceConfig{Enabled: true, Address: "http://consul:8500"}},
		ImageRebuild: ImageRebuildConfig{Enabled: true},
	}
	for _, op := range Operations(full) {
		if !sections[op] {
			t.Errorf("%q is offered but belongs to no section of the role editor", op)
		}
	}
}
